### ISSUE TITLE
Add a read method which returns only the raw value

### ISSUE THREAD

**Issue by cidzoo** [woopsa-protocol/Woopsa#1]
Now a read looks like:

``` http
GET /woopsa/read/Temperature
```

which returns:

``` json
{"Value":24.2,"Type":"Integer","TimeStamp":"Sat Jan 02 00:00:00 GMT+05:30 2010"}
```

**I suggest to add a simplier read request which would returns only the _raw value_** instead of the full _JSON payload_.

This read, called here _rawread_, would look like that instead:

``` http
GET /woopsa/rawread/Temperature
```

which would simply returns:

``` json
24.2
```

In my opinion, this could be valuable in two main aspects:
1. It removes the need to have a JSON parser for simple use cases
2. It permits a much lighter payload

This simplier request could be very useful for embedded systems with limited resources as well as for even quicker use of the web REST woopsa API for some simple use cases. Moreover, a raw value beeing also considered as a JSON object, this could still be used with a JSON parser as well.

**Comment by floriansegginger** [comment]
Thanks for the interesting suggestion. As we're still in the process of porting Woopsa to embedded platforms, we'll take it into consideration
