### ISSUE TITLE
Allow selective caching on the WoopsaObjectAdapter

### ISSUE THREAD

**Issue by floriansegginger** [woopsa-protocol/Woopsa#12]
Currently, the `CheckCache` delegate can be used on the `WoopsaServer` to selectively choose which paths are cached or not.

However, in cases where one uses the `WoopsaObjectAdapter` (in the default `WoopsaServer` constructor for example), there is no way to selectively cache (or not) certain objects. This makes working with `IEnumerable`s a bit complicated, as the whole cache needs to be cleared.

**Comment by francoisbirling** [comment]
The caching mechanism appeared to have very low impact on overall performances. In addition, it was difficult to use with dynamic object hierarchies (hierarchies that changes dynamically at runtime).

Accordingly, to keep woopsa as simple as posible, path-caching mechanism has been removed from C# server implementation. Global performances of woopsa have also been optimized by introducing hashtables were it was efficient.
