### ISSUE TITLE
Add support for OPTIONS requests in all Woopsa server implementations to support authentication

### ISSUE THREAD

**Issue by floriansegginger** [woopsa-protocol/Woopsa#21]
As of today, authentication in the Woopsa protocol does not work when using the JavaScript client (browser) library, if the server resides on a different domain-name than the page making the requests.

This is a situation which can appear when HTML pages are making requests to "independent" Woopsa servers.

The problem seems to come from the rather recent CORS specification (see [this StackOverflow issue](http://stackoverflow.com/questions/15734031/why-does-the-preflight-options-request-of-an-authenticated-cors-request-work-in) for some discussion on the subject)

**The problem did not appear during earlier development as there was a bug in Chrome that made it not respect the CORS specifications 100%.**
## Technical details

When one wishes to make a _cross-domain_ HTTP request from a JavaScript page, there are some security implications. To remedy this, the W3C has come up with a _"great"_ solution that is [_CORS: Cross-origin resource sharing_ combined with _pre-flight headers_ ](https://en.wikipedia.org/wiki/Cross-origin_resource_sharing)

What this means is that any XMLHTTPRequest (AJAX) request from a page may not be made to a server on a different domain directly. Instead, the browser needs to know if this request is "allowed". It does this by making an HTTP `OPTIONS` request before making the actual `GET` or `POST` request.

If a server accepts cross-domain requests, it should reply with something like

```
Access-Control-Allow-Origin: http://foo.com
Access-Control-Allow-Methods: GET, POST
```

But it should **not** execute any action. If this reply satisfies the browser, then it will make the actual request.

This doesn't seem like much of a problem in most cases, as current Woopsa server implementations treat `OPTIONS` requests like any others and actually already send these `Access-Control-Allow-*` headers in every situation. _However_, this could be a problem with the _Invoke_ Woopsa action, since requests _will be made twice_. 

The problem becomes really _problematic_ when we add Authentication to a Woopsa server. This is because the _CORS_ specification **explicitly forbids** user credentials to be sent in the `OPTIONS` request. Thus, Woopsa servers won't see any credentials and will just reply with HTTP error `401: Authentication Required`. 
## Solving the problem

To solve this rather complicated problem, Woopsa servers need to be modified to handle `OPTIONS` requests in a clean way. Be careful, however, as this might have some high-level implications:
- When an `OPTIONS` request is received by a server, it should send the currently-sent HTTP headers (Access-Control-Allow-Origin, etc.)
- However, it **should never** take any action. For example, it should not actually invoke the method, write or read the variable. **This is of utmost importance**, as most browsers will issue the first request twice.
## Work-around

To get around this problem, use the content-serving abilities of the different Woopsa server implementations to host JavaScript and HTML. This will make it so HTML+JS is hosted on the same domain as the Woopsa server, and will avoid this cross-domain CORS nonsense.

**Comment by francoisbirling** [comment]
A customizable implementation of CORS mechanisms has been integrated into Woopsa C#, into the WebServer class.
