### ISSUE TITLE
Using Woopsa as a bridge to OPC UA server

### ISSUE THREAD

**Issue by jugglingcats** [woopsa-protocol/Woopsa#23]
Hi, am interested in using Woopsa node server to bridge to OPC UA. The homepage has the tantalising statement: "_Because Woopsa shares so many concepts with OPC-UA, you can also use it as a gateway server to connect your webapps to OPC-UA servers._"

Is there any more information about how to do this? I'm happy to write some bridging code, but it's not clear how to get started.

Thanks

**Comment by francoisbirling** [comment]
Hi

In fact, you simply have to create a C# class that implements the IWoopsaObject interface, and that publishes the sub nodes (Items property), the methods (Methods property) and the Properties of the object model. Giving an instance of your own IWoopsaObject to the constructor of a WoopsaServer instance will complete the development of your bridge.

Many classes in Woopsa library simplifies the  job to implement IWoopsaObject (simply derive from WoopsaObject classe and populate ).

Please have a look at the project Woopsa/Sources/BeckhoffAds/. This contribution demonstrates how to implement a bridge. It realizes the bridging with the ADS protocol for Beckhoff PLC. Please have a look at the WoopsaAdsServer.cs method loadHierarchy that illustrates how to populate a WoopsaObject from the ADS data. It should be very similar to populate  the hierarchy with information got from an OPC-UA client.

Hope this will help.

**Comment by jugglingcats** [comment]
Hi thanks for info but we are using nodejs not c#.

**Comment by floriansegginger** [comment]
Hello,

Doing it in NodeJS is easy as well.

The default JavaScript object to WoopsaObject reflector was designed with basic scenarios in mind. As such, you just have to create the `WoopsaObject` yourself, adding methods and properties as you traverse your OPC-UA server.

For example, you could do something like this:

```javascript
var types = require('woopsa').Types;
var bridge = new types.WoopsaObject("Name of root object");

// To add a new property, we must first create a WoopsaPropertyAsync and add it to our WoopsaObject
var propertyTest = new types.WoopsaPropertyAsync(
  "name",  // the name of this property
  "Real",  // the type of this property
  function onRead(done) {
    // do stuff and get the value of your OPC-UA property
    done(42); // When read, this property will return 42
  }, 
  function onWrite(value, done) {
    // write the value somewhere
    done(value); // When done writing, call the done callback with the written value
 }
);
bridge.addProperty(propertyTest);

// You can also add functions
var methodTest = new types.WoopsaMethodAsync(
  "name",  // the name of this method
  "Real",  //the return type of this method
  function onInvoke(arguments, done) {
    // do stuff and call your method in OPC-UA
    done(42); // returns 42
  }, 
  [] // Array of WoopsaMethodArgumentInfo
);
bridge.addMethod(methodTest);

// And add internal objects, ad infinitum
var internalObject = new WoopsaObject("Name of internal object");
// Add properties and methods...
bridge.addItem(internalObject);
```

Once you have your WoopsaObject, you can just create a server like you normally would.

```javascript
var woopsa = require('woopsa');
var server = new WoopsaServer(
  bridge, 
  {} // parameters go here
);
```

It will help to download the source code and go check out the simple-server.js demo, as well as going a little deeper and checking types.js

I'm guessing you will have to use the node-opcua library available here: http://node-opcua.github.io/

If you do manage to finish something, it will be greatly appreciated if you could make a pull request with your code!
