### ISSUE TITLE
.net core issues

### ISSUE THREAD

**Issue by fabien-chevalley** [woopsa-protocol/Woopsa#33]
Here is some know issues on .net core target :

- [ ] [Tcp socket is not correctly shutdown for arm-linux (Raspberry pi).](https://github.com/woopsa-protocol/Woopsa/blob/14e8c31cdaf8e46505337c3b969b0ef8303118c7/Sources/DotNet/Woopsa/HTTPServer/Server/WebServer.cs#L174)
- [ ] [HttpWebRequest ServicePoint is not supported](https://github.com/woopsa-protocol/Woopsa/blob/e8e38a972ac1adcaa264decb35538ffe7f499088/Sources/DotNet/Woopsa/Client/WoopsaClientProtocol.cs#L152)

**Comment by peache85** [comment]
v 1.3 should be .net core fully compatible
