### ISSUE TITLE
C# Collection mapping

### ISSUE THREAD

**Issue by fgava** [woopsa-protocol/Woopsa#34]
Hello,
in my model I have some generic collections (List<T>, Dictionary<TKey, TValue>, etc).
What are the best practices for mapping collections of objects?
Is it possible to have a simple example in which a collection is mapped and how to map and access its elements?

Thanks in advance

**Comment by peache85** [comment]
Hello Fabio,

For complex data structure you can use the Value type JsonData. 
Option A : you do your serialization at both side at your own
Option B : you can use WoopsaConverter.

Please detail more your application in order to allow us to guide you more precisely

Best regards,
Paul-Henri

**Comment by fgava** [comment]
This is the first level of my model:
```
 public class Part { 
        public string Name { get; set; }
        public string Description { get; set; }
        public int Status { get; set; }
        public List<Measure> Measures { get; set; }
    }

 public class Measure
    {
        public int Id { get; set; }
        public string Description { get; set; }
        public int Step { get; set; }
        public double Value { get; set; }
    }
```
I have a web/REST background so I am used to access resources like this:

```
parts/
parts/1   
parts/1/description
parts/1/measures
parts/1/measures/2
parts/1/measures/2/value
```
For properties, access is very similar, but for the collections I probably did not understand how to model my hierarchy in the right way.

Thanks for the help!

**Comment by JuergenBinder** [comment]
Dear Fabio,

I have a simular data model.
Thanks for your effort! I am looking forward to seeing the answer.

Regards, Jürgen

**Comment by peache85** [comment]
Hi,
I assume that your server is C# .Net.
Collection of instance are managed directly by Woopsa. Example: `List<Measure> Measures` would work directly at least if you have the `WoopsaVisibility.IEnumerableObject` attribute.
A Dictionary as a complex collection need a converter to be serialized into json back and forth.
Do you see how to make such a converter ?
What is your client nature ? C# .Net as well ?
Best regards,
Paul-Henri

**Comment by peache85** [comment]
Hi Everybody,
To visualize what your server is publishing I can propose you this free tool : https://www.objectis-software.com/product/ostudio-live-tuning-live-debugging-functional-tests/

Add a LiveTuning project and add a woopsa connection. Then you can easily navigate into the model through the treeview. (F5 to update branch)

Best regards,
Paul-Henri

**Comment by fgava** [comment]
Yes both C#.

This is my example code:

```
using System;
using System.Collections.Generic;
using System.Net.Sockets;
using Woopsa;

namespace WoopsaDemoServer
{
    [WoopsaVisibilityAttribute(WoopsaVisibility.DefaultIsVisible)]
    public class Part
    {
        public Part()
        {
            Measures = new List<Measure>();
            for (int i = 0; i < 10; i++)
            {
                Measures.Add(new Measure { Id = i, Description = "Desc" + i, Step = i, Value = i });
            }
        }
        public string Name { get; set; }
        public string Description { get; set; }
        public int Status { get; set; }
        public List<Measure> Measures { get; set; }
    }

    [WoopsaVisibility(WoopsaVisibility.IEnumerableObject)]
    public class Measure
    {
        public int Id { get; set; }
        public string Description { get; set; }
        public int Step { get; set; }
        public double Value { get; set; }
    }

    class Program
    {
        static void Main(string[] args)
        {
            try
            {
                Part root = new Part();
                bool done = false;
                using (WoopsaServer woopsaServer = new WoopsaServer(root, 8080))
                {

                    Console.WriteLine("Woopsa server listening on http://localhost:{0}{1}", woopsaServer.WebServer.Port, woopsaServer.RoutePrefix);
                    Console.WriteLine("Some examples of what you can do directly from your browser:");
                    Console.WriteLine(" * View the object hierarchy of the root object:");
                    Console.WriteLine("   http://localhost:{0}{1}meta/", woopsaServer.WebServer.Port, woopsaServer.RoutePrefix);
                    Console.WriteLine(" * Read the value of a property:");
                    Console.WriteLine("   http://localhost:{0}{1}read/Temperature", woopsaServer.WebServer.Port, woopsaServer.RoutePrefix);


                    Console.WriteLine();
                    Console.WriteLine("Commands : QUIT, AUTH, NOAUTH");
                    do
                    {
                        Console.Write(">");
                        switch (Console.ReadLine().ToUpper())
                        {
                            case "QUIT":
                                done = true;
                                break;
                            case "AUTH":
                                woopsaServer.Authenticator = new SimpleAuthenticator(
                                    "WoopsaDemoServer",
                                    (sender, e) => { e.IsAuthenticated = e.Username == "woopsa"; });
                                break;
                            case "NOAUTH":
                                woopsaServer.Authenticator = null;
                                break;
                            default:
                                Console.WriteLine("Invalid command");
                                break;
                        }
                    }
                    while (!done);
                }
            }
            catch (SocketException e)
            {
                // A SocketException is caused by an application already listening on a port in most cases
                // Applications known to use port 80:
                //  - On Windows 10, IIS is on by default on some configurations. Disable it here: 
                //    http://stackoverflow.com/questions/30758894/apache-server-xampp-doesnt-run-on-windows-10-port-80
                //  - IIS
                //  - Apache
                //  - Nginx
                //  - Skype
                Console.WriteLine("Error: Could not start Woopsa Server. Most likely because an application is already listening on port 80.");
                Console.WriteLine("Known culprits:");
                Console.WriteLine(" - On Windows 10, IIS is on by default on some configurations.");
                Console.WriteLine(" - Skype");
                Console.WriteLine(" - Apache, nginx, etc.");
                Console.WriteLine("SocketException: {0}", e.Message);
                Console.ReadLine();
            }
        }
    }
}
```

and this is the response of the server (_http://localhost:8080/woopsa/meta_):
```
{
   "Name":"Part",
   "Items":[
      "SubscriptionService"
   ],
   "Properties":[
      {
         "Name":"Name",
         "Type":"Text",
         "ReadOnly":false
      },
      {
         "Name":"Description",
         "Type":"Text",
         "ReadOnly":false
      },
      {
         "Name":"Status",
         "Type":"Integer",
         "ReadOnly":false
      }
   ],
   "Methods":[
      {
         "Name":"MultiRequest",
         "ReturnType":"JsonData",
         "ArgumentInfos":[
            {
               "Name":"Requests",
               "Type":"JsonData"
            }
         ]
      }
   ]
}
```
Where am I wrong?

Any further example, like the dictionary converter, it would be really helpful.

Thanks

**Comment by peache85** [comment]
`[WoopsaVisibility(WoopsaVisibility.IEnumerableObject)] ` should be put on class Part in order to publish the property `Measures` 
`[WoopsaVisibilityAttribute(WoopsaVisibility.DefaultIsVisible)]` can be put on class Measure so that the properties will be published.

Could you please test the modification and let me know ?

**Comment by fgava** [comment]
In this way all the properties are gone:
```
{
   "Name":"Part",
   "Items":[
      "SubscriptionService"
   ],
   "Properties":[

   ],
   "Methods":[
      {
         "Name":"MultiRequest",
         "ReturnType":"JsonData",
         "ArgumentInfos":[
            {
               "Name":"Requests",
               "Type":"JsonData"
            }
         ]
      }
   ]
}
```

**Comment by peache85** [comment]
Sorry I haven't tried to run your code.

With this model, it will work as expected :

```
[WoopsaVisibility(WoopsaVisibility.DefaultIsVisible | WoopsaVisibility.IEnumerableObject)]
    
    public class Part
    {
        public Part()
        {
            Measures = new List<Measure>();
            for (int i = 0; i < 10; i++)
            {
                Measures.Add(new Measure { Id = i, Description = "Desc" + i, Step = i, Value = i });
            }
        }
        public string Name { get; set; }
        public string Description { get; set; }
        public int Status { get; set; }
        public List<Measure> Measures { get; set; }
    }


    public class Measure
    {
        public int Id { get; set; }
        public string Description { get; set; }
        public int Step { get; set; }
        public double Value { get; set; }
    }
```

**Comment by fgava** [comment]
Great, now the example works!

Here is the code:
```
[WoopsaVisibility(WoopsaVisibility.DefaultIsVisible | WoopsaVisibility.IEnumerableObject)]
public class Part
{
    public Part()
    {
        Measures = new List<Measure>();
        for (int i = 0; i < 10; i++)
        {
            Measures.Add(new Measure { Id = i, Description = "Desc" + i, Step = i, Value = i });
        }
    }
    public string Name { get; set; }
    public string Description { get; set; }
    public int Status { get; set; }
    public List<Measure> Measures { get; set; }
}


public class Measure
{
    public int Id { get; set; }
    public string Description { get; set; }
    public int Step { get; set; }
    public double Value { get; set; }
}
```
Is it possible to change the default name for a collection item (Item0, Item1.. etc) to a custom one? (maybe more readable)

What is the best way to retrieve all the properties in a single call? I have to read the structure of the object using meta, then request all the properties through a MultiRequest? Is it better to provide a method for this specific task? Is there any simpler solution?

Thanks

**Comment by peache85** [comment]
**# Item name and how collection works :**
The "item" name depends on how the server implementation publish collections. The C# woopsa server implementation observe the model collection and uses the name "item" followed by an index for each item added in the Enumeration. Then the field "OrderedItemIds" tells the client that the collection has changed. This way Add, Remove, Move can be detected when the "OrderedItemIds" change. Usually the client subscribes to this field so that any change in the model collection will be noticed by the client.

**# Retrieve data** 
```
Example of code that retrieve the measure data and print out :
var root = client.CreateBoundRoot();
var Measures = root.Items["Measures"] as WoopsaObject;
int i = 0;
foreach (var item in Measures.Items.Cast<WoopsaObject>())
{
    Console.WriteLine("Measure " + i++);
    int id = item.Properties[nameof(Measure.Id)].Value;
    string description = item.Properties[nameof(Measure.Description)].Value;
    int step = item.Properties[nameof(Measure.Step)].Value;
    double value = item.Properties[nameof(Measure.Value)].Value;
    Console.WriteLine($"id: {id} description:{description} step: {step} value: {value}");
}
```


**#Meta data**
Meta data are only used to discover dynamically the data structure published by the server side. In client-server application where you program both side, meta data are not needed because you know in advance the data structure. See my exemple of code, there is no meta data request.


What do you mean by "retrieve all the properties" ? Is it the structure (meta data) or the list content ?

**Comment by peache85** [comment]
Dear   Jürgen,

Are the comments useful for you and your case? Otherwise I would suggest to open another issue.

Best regards,
Paul-Henri

**Comment by JuergenBinder** [comment]
Dear Paul-Henri,

thanks a lot. I am happy with the answer.

Regards, Jürgen

**Comment by fgava** [comment]
Ok, now it's clearer!
You said the field "OrderedItemIds" tells the client that the collection has changed (Add, Remove, Move), but there is no notification of which Measure has changed right? How can I know what Measure has changed? Do I have to loop Measures every time?
Is it possible to be notified, for example, when a property of a measure has changed and get the instance of the Measure object with all its properties inside the notification? (even in JSON)

```
Server                                                                Client
Measure[1].Value = 1; ====> Notification ==> Measure[1]
```


Thanks for your patience :)

**Comment by peache85** [comment]
Dear Fabio,

No problem.

"OrderedItemIds" indicates the collection has changed: 
+ Add an Item will add an incremented index to the OrderedItemIds list
+ Remove an Item will reduce the OrderedItemIds list of indexes
+ Move an Item will move the index into the OrderedItemIds list.

If you want to detect a modification of a property on one of your Measure in the list, (in this case the list isn't changed), you can subscribe to this property changed. The publish-subscribe mechanism is there to synchronize client model.

Is the answer clear enough for you?
Best regards,
Paul-Henri
