### ISSUE TITLE
MultiRequest Javascript Client

### ISSUE THREAD

**Issue by bnjroos** [woopsa-protocol/Woopsa#35]
Hello,

Thank you for your awesome work. 
Could you explain how to implement the MultiRequest method on a javascript client ?

Is it just by using:

`client.MultiRequest(jsonarray, ....`

Thank you in advance,

**Comment by peache85** [comment]
Hi,

As you can see in the source code, the requests are structured as following:
Id
Verb (meta, invoke, read, write)
Path
Value
Arguments


Be sure that your server as the multirequest functionality. To validate that verify that the server publishes a MultiRequest object at the root.

Best regards,
Paul-Henri

**Comment by bnjroos** [comment]
Thank you for your answer, actually I just realized that the multirequest seems to work when i use the demo server that requires the index.js file in the package root folder however when I use my own file with a 
`var woopsa = require('woopsa');` it does not seem to work.

**Comment by peache85** [comment]
I assume that your use the NodeJs server, right ?

Could you please check that the "meta" verb from the client side will give you the MultiRequest object ?

Just to understand if the trouble is server side or client side.

**Comment by bnjroos** [comment]
Yes I am using the NodeJS server.
Ok I think I found the culprit. 
When I download the woopsa-master.zip directly from the website here: http://www.woopsa.org/download/ , the multirequest object is available at root and I can invoke the MultiRequest Method. 
However when I use npm to install the package, the multirequest object is available at root but when I invoke the MultiRequest method I get:
`POST http://localhost/woopsa/invoke/MultiRequest 400 (Bad Request)`

By using the downloaded files, it is now working.

**Comment by peache85** [comment]
Happy to hear that it's working well.

So if I understand well, the npm package seems to be buggy ?

Thanky for your answers in order to fix this if needed.

**Comment by bnjroos** [comment]
Yes indeed, the npm package seems to be buggy. Using the npm package and exactly the same code I do not manage to invoke the MultiRequest method.

- If I run simple-server.js included in the npm package, I get: POST http://localhost/woopsa/invoke/MultiRequest 400 (Bad Request)

- If I run simple-server.js included in the Woopsa-master.zip downloaded on the website, I get the correct return value.
