### ISSUE TITLE
Enhancement: dynamic properties

### ISSUE THREAD

**Issue by phryniszak** [woopsa-protocol/Woopsa#36]
It would be nice to have option to define dynamic property. By dynamic I understand property that is resolved during program execution. Lets say I have server for PLC and I want to serve I/O. Instead of defining each I/O as bool, byte, word i would like to have one route lets say /io and based on request resolve it to proper value.

**Comment by francoisbirling** [comment]
Hi,

This request enters in contradiction with the main assumption that an object publishes the list of methods, properties and contained elements, used by the "meta" verb of the Woopsa protocols. Such list could not be established for an object with dynamic properties.

I propose two alternative solutions :
Solution A) Define a remote method to query IO value based on names defined ni each request : IO/GetValue(IoName)
Solution B) If you absolutely need properties for items defined by the client requests : Create a remote method CreateIoProperty (Name, WoopsaType) that creates the corresponding property upon request. This method should simply create a new WoopsaProperty in the WoopsaObject Io.

Hope this will help.
