### ISSUE TITLE
Subscribe method does not accept backslash in path

### ISSUE THREAD

**Issue by AoiMasa** [woopsa-protocol/Woopsa#56]
**Problem description**
It seems the Subscribe method from WoopsaClientSubscriptionChannel does not handle backslash in path. It doesn't throw an exception but it doesn't work at all.

It can be confusing because the output given by oMachine use backslash instead of slash and the Read method supports backslash as well.

**Current behaviour:**
 client.SubscriptionChannel.Subscribe(@"Thermostat\SetPoint", (e, a) =>
            {
              ...
            });
=> KO

 client.SubscriptionChannel.Subscribe("Thermostat/SetPoint", (e, a) =>
            {
              ...
            });
=> OK

var point =  client.ClientProtocol.Read(@"Thermostat\SetPoint") 
=> OK

**Expected behaviour**
Subscribe method should handle backslash in the path:

 client.SubscriptionChannel.Subscribe(@"Thermostat\SetPoint", (e, a) =>
            {
              ...
            });
=> OK

**Comment by peache85** [comment]
Hi,
I assume that oMachine correspond to oStudio. Indeed, this tool gives you currently the link to a node using backslash. This tool should be adapted.

To come back to Woopsa, the Woopsa path separator is defined as a constant as a slash. If you respect the convention of the arguments of the Subscription service, it will work as expected.
The fact that the Read support both is a URL .Net Feature. 

Add a replace statement from backslah to slash everywhere woopsa path argument is used has not be chosen as an option.

Hoping that everything is clear for you,

Best regards,
Paul-Henri
