### ISSUE TITLE
Send large content from Client to Server

### ISSUE THREAD

**Issue by fabien-chevalley** [woopsa-protocol/Woopsa#6]
Hi,

How can I send a file from Client to Server ?

I try to send my file as a string, but the request buffer seems to be too small, is it limited to 10ko ?
So I try to upload my file using standard webclient.uploadfile but the server doesn't recognized this command.

How can I proceed to send a large file ?

Thank for the help,
Fabien

**Comment by floriansegginger** [comment]
Issue moved to #7
