### ISSUE TITLE
Chrome ERR_SSL_PROTOCOL_ERROR This site can’t provide a secure connection. localhost sent an invalid response.

### ISSUE THREAD

**Issue by AndrejKXX** [woopsa-protocol/Woopsa#62]
When I am running the DotNet WoopsaDemoServer and I write "http://localhost:54004/woopsa/read/Temperature" in the Google Chrome browser (Latest Version 89.0.4389.72 (Official Build) (64-bit)), I get "This site can’t provide a secure connection localhost sent an invalid response. Try running Windows Network Diagnostics. ERR_SSL_PROTOCOL_ERROR".
This happens because the browser automatically changes http:// to https:// when I press enter. It works well if I write "http://127.0.0.1:54004/woopsa/read/Temperature".
You might put a warning in your Quick Start Guide.
This is not a problem in Internet Explorer 11. I haven't checked any other browsers.

**Comment by peache85** [comment]
Hi, I there any option in Chrome to disabled this http to https automatic url change ?

**Comment by AndrejKXX** [comment]
Hi,
I managed to fix the problem by forcing a hard refresh:
Open the Developer Tools panel (CTRL+SHIFT+I)
Click and hold the reload icon / Right click the reload icon.
A menu will open.
Choose the 3rd option from this menu ("Empty Cache and Hard Reload").
