### ISSUE TITLE
How to use authentication with http, DotNet WoopsaDemoServer

### ISSUE THREAD

**Issue by AndrejKXX** [woopsa-protocol/Woopsa#63]
I am running the DotNet WoopsaDemoServer. I type "AUTH [enter]". Then I write "http://127.0.0.1:54004/woopsa/read/Temperature" in Google Chrome. I get the response "{"Value":24.2,"Type":"Real"}". I expect that I should not get access to this data because I did not provide authentication with username and password.
After that I typed "noauth [enter]" and tried again, the Google Chrome showed a Sign In popup window.
Then I tried to disable the authentication but couldn't. I also tried to open Internet Explorer 11 every time I type auth or noauth, but the popup shows up every time.
Is there some sort of long delay before the authentication is enabled or disabled?
This is repeatable: When I start the program, the server requires notification immediately only when I type "auth [enter] noauth [enter]". Why? But I cannot turn the authentication off. I am using the latest Woopsa 1.2.

**Comment by peache85** [comment]
Have you closed completely Chrome at every AUTH changes ? The password seems to by kept by the navigator until it is closed and reopen completely.

**Comment by AndrejKXX** [comment]
This problem also happens when I don't use a browser and I only use the DotNet WoopsaDemoServer and the the DotNet WoopsaDemoClient.
I have managed to resolve this issue by downloading the latest version of Woopsa 1.3.0 using MS Visual Studio, Nuget Package Manager.
https://www.nuget.org/packages/Woopsa (This version is not available at http://www.woopsa.org/)
This version works without a problem. The server immediately toggles the authentication on command.
