### ISSUE TITLE
Implement support for multipart/form-data POST requests in WebServer

### ISSUE THREAD

**Issue by floriansegginger** [woopsa-protocol/Woopsa#7]
Currently, the C# WebServer does not support `multipart/form-data`-encoded POST requests. This makes it impossible for clients to send files to servers.

Supporting this method of POST requests should be optional as it requires some additional security checks (what happens if a user tries to upload a 1TB file? etc) and creation of additional Streams. 

The `HTTPRequest` class could then contain a `Files` array of `Stream`s allowing the programmer to act on these files, for example saving them to disk or parsing them on-the-fly.

**Comment by fabien-chevalley** [comment]
Thank you for the advice.

**Comment by ChristopheJaggi** [comment]
This feature is currently **not essential** to the protocol. The protocol should remain as **simple** as possible. Therefore, we will not take into account the management of the `multipart / form-data`. A client can still send data using the `Content-Type: application / x-www-form-urlencoded`.
